spring:
  datasource:
    driver-class-name: ${custom.prod_database.driver-class-name}
    url: ${custom.prod_database.url}
    username: ${custom.prod_database.username}
    password: ${custom.prod_database.password}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false